In [15]:
import pandas as pd

# Load datasets
fuel_df = pd.read_csv("FuelConsumption.csv")
cars_df = pd.read_csv("cars_2025.csv")

# Preview both datasets
print("Fuel Consumption Data:")
display(fuel_df.head())

print("\nCars 2025 Data:")
display(cars_df.head())

Fuel Consumption Data:

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

Cars 2025 Data:

     date_reg        type  maker      model  colour         fuel        state
0  2025-01-01     motokar    BYD       Seal   white     electric  Rakan Niaga
1  2025-01-01  window_van    Cam   Placer-X  yellow  greendiesel        Johor
2  2025-01-01         jip  Chery  Jaecoo J7   green       petrol  Rakan Niaga
3  2025-01-01         jip  Chery  Jaecoo J7  silver       petrol  Rakan Niaga
4  2025-01-01         jip  Chery      Tiggo    grey       petrol  Rakan Niaga

In [17]:
print("Fuel Dataset Columns:", fuel_df.columns)
print("Cars Dataset Columns:", cars_df.columns)

# Check for missing values
print(fuel_df.isnull().sum())
print(cars_df.isnull().sum())

Fuel Dataset Columns: Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS'],
      dtype='object')
Cars Dataset Columns: Index(['date_reg', 'type', 'maker', 'model', 'colour', 'fuel', 'state'], dtype='object')
MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64
date_reg    0
type        0
maker       0
model       0
colour      0
fuel        0
state       0
dtype: int64

In [19]:
# Standardize column names
fuel_df.columns = fuel_df.columns.str.strip().str.lower().str.replace(" ", "_")
cars_df.columns = cars_df.columns.str.strip().str.lower().str.replace(" ", "_")

# Rename column 'make' in FuelConsumption to 'maker' to standardize with cars_2025
fuel_df.rename(columns={'make': 'maker'}, inplace=True)

# Drop rows with missing model or make
fuel_df.dropna(subset=['maker', 'model'], inplace=True)
cars_df.dropna(subset=['maker', 'model'], inplace=True)

print("Fuel Dataset Columns:", fuel_df.columns)
print("Cars Dataset Columns:", cars_df.columns)

Fuel Dataset Columns: Index(['modelyear', 'maker', 'model', 'vehicleclass', 'enginesize',
       'cylinders', 'transmission', 'fueltype', 'fuelconsumption_city',
       'fuelconsumption_hwy', 'fuelconsumption_comb',
       'fuelconsumption_comb_mpg', 'co2emissions'],
      dtype='object')
Cars Dataset Columns: Index(['date_reg', 'type', 'maker', 'model', 'colour', 'fuel', 'state'], dtype='object')

In [21]:
# Standardize data
for col in fuel_df.select_dtypes(include='object').columns:
    fuel_df[col] = fuel_df[col].str.lower().str.strip()

for col in cars_df.select_dtypes(include='object').columns:
    cars_df[col] = cars_df[col].str.lower().str.strip()

print("Fuel Consumption Data:")
display(fuel_df.head())

print("\nCars 2025 Data:")
display(cars_df.head())

Fuel Consumption Data:

,modelyear,maker,model,vehicleclass,enginesize,cylinders,transmission,fueltype,fuelconsumption_city,fuelconsumption_hwy,fuelconsumption_comb,fuelconsumption_comb_mpg,co2emissions
0,2014,acura,ilx,compact,2.0,4,as5,z,9.9,6.7,8.5,33,196
1,2014,acura,ilx,compact,2.4,4,m6,z,11.2,7.7,9.6,29,221
2,2014,acura,ilx hybrid,compact,1.5,4,av7,z,6.0,5.8,5.9,48,136
3,2014,acura,mdx 4wd,suv - small,3.5,6,as6,z,12.7,9.1,11.1,25,255
4,2014,acura,rdx awd,suv - small,3.5,6,as6,z,12.1,8.7,10.6,27,244

Cars 2025 Data:

     date_reg        type  maker      model  colour         fuel        state
0  2025-01-01     motokar    byd       seal   white     electric  rakan niaga
1  2025-01-01  window_van    cam   placer-x  yellow  greendiesel        johor
2  2025-01-01         jip  chery  jaecoo j7   green       petrol  rakan niaga
3  2025-01-01         jip  chery  jaecoo j7  silver       petrol  rakan niaga
4  2025-01-01         jip  chery      tiggo    grey       petrol  rakan niaga

In [23]:
# Check how many duplicate rows there are
print("Fuel duplicates:", fuel_df.duplicated().sum())
print("Cars duplicates:", cars_df.duplicated().sum())

# Show duplicate rows
print("Duplicate rows in FuelConsumption:")
display(fuel_df[fuel_df.duplicated()])

# Check how many total rows and unique rows
print("Total rows:", cars_df.shape[0])
print("Unique rows:", cars_df.drop_duplicates().shape[0])

# Show exact duplicates
display(cars_df[cars_df.duplicated()])

# Show a few row that is exactly the same
display(cars_df[cars_df.duplicated()].head(10))

# Drop exact duplicate rows
cars_df.drop_duplicates(inplace=True)

print("Duplicated rows are dropped")

Fuel duplicates: 0
Cars duplicates: 215141
Duplicate rows in FuelConsumption:

Empty DataFrame
Columns: [modelyear, maker, model, vehicleclass, enginesize, cylinders, transmission, fueltype, fuelconsumption_city, fuelconsumption_hwy, fuelconsumption_comb, fuelconsumption_comb_mpg, co2emissions]
Index: []

Total rows: 263578
Unique rows: 48437

,date_reg,type,maker,model,colour,fuel,state
9,2025-01-01,pick_up,ford,ranger,black,greendiesel,rakan niaga
10,2025-01-01,pick_up,ford,ranger,black,greendiesel,rakan niaga
11,2025-01-01,pick_up,ford,ranger,black,greendiesel,rakan niaga
15,2025-01-01,jip,great wall,haval h6,silver,hybrid_petrol,rakan niaga
16,2025-01-01,jip,great wall,haval h6,silver,hybrid_petrol,rakan niaga
...,...,...,...,...,...,...,...
263569,2025-04-30,window_van,xpeng,x9,silver,electric,rakan niaga
263570,2025-04-30,window_van,xpeng,x9,black,electric,rakan niaga
263574,2025-04-30,window_van,zeekr,009,black,electric,w.p. kuala lumpur
263575,2025-04-30,window_van,zeekr,009,black,electric,w.p. kuala lumpur
263577,2025-04-30,window_van,zeekr,009,white,electric,rakan niaga

,date_reg,type,maker,model,colour,fuel,state
9,2025-01-01,pick_up,ford,ranger,black,greendiesel,rakan niaga
10,2025-01-01,pick_up,ford,ranger,black,greendiesel,rakan niaga
11,2025-01-01,pick_up,ford,ranger,black,greendiesel,rakan niaga
15,2025-01-01,jip,great wall,haval h6,silver,hybrid_petrol,rakan niaga
16,2025-01-01,jip,great wall,haval h6,silver,hybrid_petrol,rakan niaga
18,2025-01-01,jip,great wall,haval h6,green,hybrid_petrol,rakan niaga
19,2025-01-01,jip,great wall,haval h6,green,hybrid_petrol,rakan niaga
20,2025-01-01,jip,great wall,haval h6,silver,hybrid_petrol,rakan niaga
29,2025-01-01,jip,lexus,rx,white,petrol,johor
31,2025-01-01,jip,lexus,rx,white,petrol,johor

Duplicated rows are dropped

In [25]:
# Save cleaned data into new .csv files
cars_df.to_csv("cars_2025_cleaned.csv", index=False)
fuel_df.to_csv("fuel_consumption_cleaned.csv", index=False)